# This is a basic workflow to help you get started with Actions

name: Power Platform Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Add environment variables to represent test Power Platform tenancy I provisioned
env:
  WF_APPLICATION_ID: 50a16f29-0343-4a7f-9531-a2477b18d66c
  WF_TENANT_ID: 52546350-b6d6-4457-9594-c98e0d08fd76
  RUNNER_DEBUG: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0
      with:
        environment-url: 'https://org890e1e60.crm11.dynamics.com'
        app-id: $WF_APPLICATION_ID
        client-secret: ${{ secrets.POWER_PLATFORM_SECRET_VALUE }}
        tenant-id: $WF_TENANT_ID
