# This is a basic workflow to help you get started with Actions

name: Power Platform Test Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RUNNER_DEBUG: 1
  ENVIRONMENT_URL: 'https://orgd1b10ac2.crm11.dynamics.com/'
  WF_APPLICATION_ID: '0c3b75c5-615b-46ef-bdf0-b1cb8678f3d0'
  WF_TENANT_ID: '52546350-b6d6-4457-9594-c98e0d08fd76'

jobs:
  build:
    runs-on: windows-latest

    steps:

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@0.4.0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.WF_APPLICATION_ID}}
        tenant-id: ${{env.TENANT_ID}}
        client-secret: ${{secrets.POWER_PLATFORM_SECRET_VALUE}}
        
